### ISSUE TITLE
Always KO on strlcat (6. 12. tests) 

### ISSUE THREAD

**Issue by Mbistami** [Tripouille/libftTester#15]
in ft_strlcat_test.cpp in 6. & 12. tests will always KO even if your function is functional
I used strlcat instead of ft_strlcat and still KO also in case 5. you're passing negative value to size_t parameter which is not possible.

I know you made the repo for a long time now but still you could make it clean!

Thank you!

**Comment by Tripouille** [comment]
![](https://media0.giphy.com/media/lb5nMu0UIh4YM/giphy.gif)

**Comment by Mbistami** [comment]
LOL
You need to remove the 5th case from strlcat anyways you can't compile with FLAGS with it you're passing -1 to size_t parameter moulinette would never test it but I'm enjoying the tester ❤️
