### ISSUE TITLE
No rule to make target ' bonus'

### ISSUE THREAD

**Issue by shawnteh1711** [Tripouille/libftTester#17]
I have no problem running mandatory test. But it show error during the bonus part.

make bonus -C ../Libft
make[1]: *** No rule to make target `bonus'.  Stop.
make: *** [bonus_start] Error 2

**Comment by Chinimala** [comment]
As written in the error message, your Makefile doesn't have a "bonus" rule.

**Comment by shawnteh1711** [comment]
I didn't changed the Makefile from the libftTester. What do you mean by need to have "bonus" rule?

**Comment by Chinimala** [comment]
I'm talking about YOUR makefile. It's in the libft subject

**Comment by shawnteh1711** [comment]
I see. I put all my files under LIB_FILES. So in order for me to use this test I need to store separately my bonus .c file into another variable like BONUS_FILES. And then convert to object file and make bonus rule. I just curious as other tester works for me without any bonus rule. Attached is my Makefile.

NAME := libft.a 
CC    := gcc
CFLAGS := -Wall -Werror -Wextra
LIB_FILES = ft_isalpha.c\
                  ft_isdigit.c\
                  ft_isalnum.c\
                  ft_isascii.c\
                  ft_isprint.c\
                  ft_strlen.c\
                  ft_memset.c\
                  ft_bzero.c\
                  ft_memcpy.c\
                  ft_memmove.c\
                  ft_strlcpy.c\
                  ft_strlcat.c\
                  ft_toupper.c\
                  ft_tolower.c\
                  ft_strchr.c\
                  ft_strrchr.c\
                  ft_strncmp.c\
                  ft_memchr.c\
                  ft_memcmp.c\
                  ft_strnstr.c\
                  ft_atoi.c\
                  ft_putchar.c\
                  ft_calloc.c\
                  ft_strdup.c\
                  ft_substr.c\
                  ft_strjoin.c\
                  ft_strtrim.c\
                  ft_split.c\
                  ft_itoa.c\
                  ft_strmapi.c\
                  ft_striteri.c\
                  ft_putchar_fd.c\
                  ft_putstr_fd.c\
                  ft_putendl_fd.c\
                  ft_putnbr_fd.c\
                  ft_lstnew.c\
                  ft_lstadd_front.c\
                  ft_lstsize.c\
                  ft_lstlast.c\
                  ft_lstadd_back.c\
                  ft_lstdelone.c\
                  ft_lstclear.c\
                  ft_lstiter.c\
                  ft_lstmap.c

OBJ_FILES = $(LIB_FILES:%.c=%.o)

all:  $(NAME)

$(NAME): $(OBJ_FILES)
ar rcs $(NAME) $(OBJ_FILES)

clean:
@echo "Cleaning..."
rm -rf $(OBJ_FILES)

fclean:
rm -f $(NAME)

re: fclean all

.PHONY: clean fclean all re

**Comment by Chinimala** [comment]
Then, this tester is the only one who warned you about that :)
