### ISSUE TITLE
[ft_substr] false positive?

### ISSUE THREAD

**Issue by mjy9088** [Tripouille/libftTester#19]
https://github.com/Tripouille/libftTester/blob/fed5efec440bfbd6a4b9735d8cb0f596e540b3bc/tests/ft_substr_test.cpp#L27-L29

This test might be problematic

```c
ft_substr("123456789\0Hello world!", 10, 100); // "Hello world!" expected? or undefined behavior?
```

**Comment by Tripouille** [comment]
imo if start >= len(s) an empty string allocated should be return.

**Comment by mjy9088** [comment]
May I ask why wouldn't that be considered invalid input?

There is a mention of the case where `length` is longer than the remaining length, but no mention of the case where `start` is longer than the total length.
