### ISSUE TITLE
CALLOC test 3

### ISSUE THREAD

**Issue by GlaceCoding** [Tripouille/libftTester#24]
According to this change : https://github.com/Tripouille/libftTester/commit/1deb0ccd100f572f62719ab1216725fb9cb34d68#diff-689e14dc52cf1e217c428e7eaafc3e7362b3b09e469c100769ef9ac2acb3f2b6R23

I saw some people bypassing this test with `count == SIZE_MAX || size == SIZE_MAX`, but `calloc(SIZE_MAX - 58, 1)` also not work. 😅

Maybe add something like : 

	/* 4 */ check(ft_calloc(5468, SIZE_MAX/458) == NULL);
	/* 5 */ check(ft_calloc(SIZE_MAX/4865, SIZE_MAX/54) == NULL);

Or a test on the line, I mean with more precision. 🤔

**Comment by ampuEus** [comment]
I have had the same problem, but if you execute the original function it return a NULL

**Comment by Tripouille** [comment]
```
x = a * b;
if (a != 0 && x / a != b) {
    // overflow handling
}
```

**Comment by Tripouille** [comment]
```
x = a * b;
if (a != 0 && x / a != b) {
    // overflow handling
}
```

**Comment by GlaceCoding** [comment]
Je ne comprends pas vos réponses, je disais que le test était facilement bypassable par des conditions "bateaux", et qu'il y aurait plus de sens à ajouter plus de précisions ou de rigueurs à ce nouveau test qui est un peu incomplet. 🤔

**Comment by Tripouille** [comment]
Il y aura toujours moyen de faire en sorte de passer les tests, peu importe le nombre de tests ajoutés. Ma réponse a pour but d'aider les éventuelles personnes qui prendraient la peine de regarder si leur problème n'a pas déjà fait l'objet d'une issue.
