### ISSUE TITLE
strlcat is stuck/frozen

### ISSUE THREAD

**Issue by berkaydagdeviren** [Tripouille/libftTester#28]
After I launch make strlcat it stays like that forever
<img width="1328" alt="Ekran Resmi 2022-10-05 ÖS 8 18 46" src="https://user-images.githubusercontent.com/76188403/194122628-16c32f73-8ca0-49e8-aca1-d15a9e451a7f.png">

**Comment by Chinimala** [comment]
Maybe your strlcat has an infinite loop ? Can you share the code ?

**Comment by berkaydagdeviren** [comment]
Sure! Sorry, just frustrated.

`#include "libft.h"
#include <stdlib.h>

size_t	ft_strlcat(char *dest, const char *src, size_t nb)
{
	size_t	destsize;
	size_t	srcsize;
	size_t	i;	

	srcsize = ft_strlen((char *)src);
	destsize = ft_strlen((char *)dest);
	if (nb - 1 <= destsize)
		return (srcsize + nb);
	i = 0;
	while (destsize + i < nb - 1)
	{
		dest[destsize + i] = src[i];
		i++;
	}
	dest[destsize + i] = '\0';
	return (destsize + srcsize);

}`

**Comment by Chinimala** [comment]
Tripouille found the problem in your function :) check the edge cases

**Comment by berkaydagdeviren** [comment]
Thank you so much! I added

```
if (!nb)
return (0);
```
Now, it goes through 4 tests and gets stuck. That must mean I have more edge cases right?

**Comment by berkaydagdeviren** [comment]
Done!
