### ISSUE TITLE
idk what this is please take a look

### ISSUE THREAD

**Issue by azeek21** [Tripouille/libftTester#31]
<img width="650" alt="Screen Shot 2022-10-13 at 18 52 55" src="https://user-images.githubusercontent.com/91887882/195645303-469c47b2-d438-40f8-8434-006c52280ed8.png">

**Comment by Chinimala** [comment]
Hello, you should find the solution just by looking at the error message, what have you checked, what have you tried, if not already resolved ?

**Comment by azeek21** [comment]
Hi, I kinda feel like am acting stupid, I don't want to though.

What I understood is, it can't find a reference to my ft_memset function. But it's there. I tried changing your makefile tests order to check other functions than memset thinking maybe it's the only one with this issue. It's seems it's not, I had same error with other functions too. At this point I don't really know what's wrong. my header file and .c files are there and libft successfully compiles. 

sorry to bother (

**Comment by Chinimala** [comment]
It may come from your Makefile then. The function seems to not be in your library. Can you check and show your Makefile ?

**Comment by azeek21** [comment]
MAKEFILE:
`
NAME = 		libft.a
CC = 		gcc
CFLAGS =	-Wall -Werror -Wextra
AR = 		ar rcs
HEAdER = 	libft.h
BIN_DIR = 	bin
TARGET = $(NAME)

SRCS =	ft_atoi.c ft_bzero.c ft_calloc.c		\
		ft_countchar.c ft_dup_matrix.c			\
		ft_extend_matrix.c ft_free_matrix.c		\
		ft_isalnum.c ft_isalpha.c ft_isascii.c	\
		ft_isdigit.c ft_isprint.c ft_isspace.c	\
		ft_itoa.c ft_lstadd_back.c ft_lstclear.c\
		ft_lstlast.c ft_lstnew.c ft_lstsize.c	\
		ft_matrix_replace_in.c ft_matrixlen.c	\
		ft_memccpy.c ft_memchr.c ft_memcpy.c	\
		ft_memcmp.c ft_memmove.c ft_memset.c	\
		ft_putchar_fd.c ft_putendl_fd.c			\
		ft_putmatrix_fd.c ft_putnbr_fd.c		\
		ft_putstr_fd.c ft_split.c ft_strchr_i.c	\
		ft_strchars_i.c ft_strchr.c ft_strdup.c	\
		ft_strjoin.c ft_strlcat.c ft_strlcpy.c	\
		ft_strlen.c ft_strmapi.c ft_strncmp.c	\
		ft_strnstr.c ft_strrchr.c ft_strtrim.c	\
		ft_substr.c ft_tolower.c ft_toupper.c	\
		ft_nbrlen.c

OBJS = $(SRCS:.c=.o)

all: $(TARGET)
	@ $(AR) $(TARGET) $(OBJS) && echo $(NAME) is up to date !

$(TARGET): $(OBJS)

$(OBJS): $(SRCS)
	$(CC) $(CFLAGS) -c $< -o $@


clean:
	rm -rf *.o

fclean: clean
	rm -rf *.o *.a *.so *.out

re: fclean all

norminette:
	norminette -R CheckForbiddenSourceHeader *


.PHONY: all norminette re fclean clean
`

Oh by the way, is it supposed to work on Linux?🥲 I am on Ubuntu 20XX

**Comment by Chinimala** [comment]
And have you tested your functions yourself ? Did a little main.c, tried to call ft_memset ?

**Comment by azeek21** [comment]
LoL. Yeah, I tested it before coming to your tests and It worked somehow. Just tried and it didn't work with my own main.c too. Then I realized I was compiling it wrong way. Now I got everything working. Thanks for directing me :)

**Comment by makayun** [comment]
Hi guys!
I'm having exactly the same issue - the same error message and on the memset function too...
How did you solve this, please?

**Comment by azeek21** [comment]
> Hi guys! I'm having exactly the same issue - the same error message and on the memset function too... How did you solve this, please?

Hi, I don't exactly remember what I did. But reading through above conversation I understood that I was compiling my libft the wrong way so that libftTester couldn't find it. Make your simple main function in another file and try to use functions from your libft. This is how I found out I was compiling it the wrong way. Hope this helps.  :heart:

**Comment by azeek21** [comment]
> Hi, sorry, I realized the next day that I had some garbage left from another tester in the folder facepalmfacepalmfacepalm But I really appreciate your response, huge thanks!

Keep up the great job :+1:
