### ISSUE TITLE
Missing check

### ISSUE THREAD

**Issue by C4rl2** [Tripouille/libftTester#35]
Hello ! I've been testing my bonus with your tester, but when it comes to ft_lstdelone, the tester doesn't print anything on the term. Looking at the ft_lstdelone_test.cpp file, I see that there is no CHECK function like in all the other *test.cpp files. Is there indeed something missing ? Thanks in advance !

**Comment by Chinimala** [comment]
Hello, it's normal, this test doesn't check any value, it only ensures that there's no leak (and that a program using your function doesn't crash, of course).
