### ISSUE TITLE
Aren't calloc(x,0) != NULL checks too strict?

### ISSUE THREAD

**Issue by Kycilak** [Tripouille/libftTester#41]
Hello,
I see that calloc tests 6, 7, 8, 10 and 11 check that the returned pointer is not a NULL when either argument is 0.
The documentation on malloc, calloc... says the following:

"NULL may also be returned by a successful call to malloc() with a size of zero, or by a successful call to calloc() with nmemb or size equal to zero."

My question is: What is the reason behind the check against NULL in the mentioned test cases?
Thank you for making this project, it is very nice and useful.
Bey

**Comment by servettonga** [comment]
Discussed in #40
