### ISSUE TITLE
KO on Moulinette at ft_strrchr.c function

### ISSUE THREAD

**Issue by u-santos** [Tripouille/libftTester#5]
Assuming I have a string "taxtripouille" and I search for the last occurrence of the character "x", the code returned null instead of "xtripouille".

**Comment by Tripouille** [comment]
Hi, char s3[] = "taxtripouille"; /* 7 */ check(ft_strrchr(s3, 'x') == s3 + 3); showLeaks(); should be s3 + 2.

**Comment by Tripouille** [comment]
Hi, if you want me to add specific test for your case please use the makefile command sendfunction, for your case make sendstrrchr.  README: If all your tests are OK (with valgrind) and the moulinette KO you, please send an email with make sendfunction ex: make sendsubstr or contact me on slack/discord for improvements.
