### ISSUE TITLE
KO: strsplit

### ISSUE THREAD

**Issue by wwwwelton** [Tripouille/libftTester#6]
A friend get killed in this test in the strsplit and passed in all of ur tests.

char *str = "1-2-3-4-5-6-7-8--8-8--8-4------4--4" 
char *sep = '-'

char *str = "--1-2-3-4-5-6-7-8--8-8--8-4------4--4" 
char *sep = '-'

Expected result: 1-2-3-4-5-6-7-8-8-8-8-4-4-4

RES[0]: $1$     -> 0x602000000210
RES[1]: $2$     -> 0x602000000230
RES[2]: $3$     -> 0x602000000250
RES[3]: $4$     -> 0x602000000270
RES[4]: $5$     -> 0x602000000290
RES[5]: $6$     -> 0x6020000002b0
RES[6]: $7$     -> 0x6020000002d0
RES[7]: $8$     -> 0x6020000002f0
RES[8]: $8$     -> 0x602000000310
RES[9]: $8$     -> 0x602000000330
RES[10]: $8$    -> 0x602000000350
RES[11]: $4$    -> 0x602000000370
RES[12]: $4$    -> 0x602000000390
RES[13]: $4$    -> 0x6020000003b0
RES[14]: $(null)$       -> (nil)

**Comment by Tripouille** [comment]
Hey,
Thanks for your feedback, I've added some tests for your case.
